version: "3.8"
services:
  app:
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app:rw
      - /usr/src/app/node_modules
    env_file:
      - .env.local
